import os
import sys
import time
import subprocess
import argparse
import json
try:
    from dotenv import load_dotenv
except ImportError:
    print("Please install python-dotenv: pip install python-dotenv")
    sys.exit(1)

# Load environment variables from .env file
load_dotenv()

# Auto-escalate to sudo if not root
if os.geteuid() != 0:
    mac_password = os.getenv("MAC_PASSWORD")
    if not mac_password:
        print("Please set MAC_PASSWORD in .env file or run this script with sudo.")
        sys.exit(1)
        
    print("Elevating privileges with password from .env...")
    # Re-run the script with sudo
    cmd = ['sudo', '-S', sys.executable] + sys.argv
    p = subprocess.Popen(cmd, stdin=subprocess.PIPE, universal_newlines=True)
    try:
        p.communicate(mac_password + '\n')
    except KeyboardInterrupt:
        pass
    sys.exit(p.returncode)

# These imports must happen after the sudo check to ensure they don't break if run as non-root
from macimu import IMU
from motion_live import VibrationDetector
from collections import deque

def play_sound(mp3_path):
    """Play the sound using macOS built-in afplay in the background"""
    subprocess.Popen(["afplay", mp3_path])

def load_calibration(path):
    """Load a calibration profile generated by calibrate.py"""
    if not os.path.exists(path):
        print(f"Warning: Calibration file '{path}' not found, using defaults.")
        return None
    try:
        with open(path, 'r') as f:
            cal = json.load(f)
        print(f"Loaded calibration: sensitivity={cal.get('sensitivity', '?')}, "
              f"noise_floor={cal['baseline']['noise_floor']:.6f}g, "
              f"trigger={cal['thresholds']['trigger_magnitude']:.6f}g")
        return cal
    except Exception as e:
        print(f"Warning: Failed to load calibration: {e}")
        return None

def main():
    parser = argparse.ArgumentParser(description="Play an MP3 when MacBook vibrates continuously.")
    parser.add_argument("mp3_file", nargs='?', default="/Users/e27/Desktop/accelerometer/apple-silicon-accelerometer/k.mp3", help="Path to the custom .mp3 file")
    parser.add_argument("--cooldown", type=float, default=None, help="Cooldown in seconds between sounds (default: 2.0)")
    parser.add_argument("--timeframe", type=float, default=None, help="How many seconds the vibration must be continuous to trigger (default: 2.0)")
    parser.add_argument("--tolerance", type=float, default=None, help="Seconds of quiet allowed before resetting the continuous timer (default: 0.5)")
    parser.add_argument("--calibration", "-c", type=str, default=None, help="Path to calibration.json from calibrate.py")
    args = parser.parse_args()

    # Load calibration profile
    cal = None
    if args.calibration:
        cal = load_calibration(args.calibration)
    else:
        # Auto-detect calibration.json in same directory
        auto_cal = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'calibration.json')
        if os.path.exists(auto_cal):
            cal = load_calibration(auto_cal)

    # Apply calibration or defaults (CLI flags override calibration)
    if cal:
        thresholds = cal['thresholds']
        cooldown = args.cooldown if args.cooldown is not None else thresholds.get('cooldown', 2.0)
        timeframe = args.timeframe if args.timeframe is not None else thresholds.get('timeframe', 2.0)
        tolerance = args.tolerance if args.tolerance is not None else thresholds.get('tolerance', 0.5)
        severity_filter = thresholds.get('severity_filter', ['CHOC_MAJEUR', 'CHOC_MOYEN', 'MICRO_CHOC', 'VIBRATION', 'VIB_LEGERE'])
        trigger_magnitude = thresholds.get('trigger_magnitude', 0.0)
        noise_floor = cal['baseline'].get('noise_floor', 0.0)
    else:
        cooldown = args.cooldown if args.cooldown is not None else 2.0
        timeframe = args.timeframe if args.timeframe is not None else 2.0
        tolerance = args.tolerance if args.tolerance is not None else 0.5
        severity_filter = ['CHOC_MAJEUR', 'CHOC_MOYEN', 'MICRO_CHOC', 'VIBRATION', 'VIB_LEGERE']
        trigger_magnitude = 0.0
        noise_floor = 0.0

    if not os.path.exists(args.mp3_file):
        print(f"Error: The sound file '{args.mp3_file}' does not exist.")
        sys.exit(1)

    print(f"Listening for continuous vibration ({timeframe}s)...")
    print(f"  Cooldown: {cooldown}s | Tolerance: {tolerance}s")
    if trigger_magnitude > 0:
        print(f"  Trigger magnitude: {trigger_magnitude:.6f}g | Noise floor: {noise_floor:.6f}g")
    print(f"  Severity filter: {', '.join(severity_filter)}")
    print(f"  Will play: {args.mp3_file}")
    
    last_play_time = 0
    detector = VibrationDetector(fs=100)
    last_evt_count = 0
    
    # State tracking for continuous vibration
    vibration_start_time = None
    last_vibration_time = None

    with IMU(sample_rate=100) as imu:
        while True:
            # Read new accelerometer samples with hardware timestamps
            samples = imu.read_accel_timed()
            if not samples:
                time.sleep(0.01)
                continue

            # Process samples through the advanced VibrationDetector
            for s in samples:
                detector.process(s.x, s.y, s.z, s.t)
            
            # Print live value to console so user can see activity
            mag = detector.latest_mag
            sys.stdout.write(f"\r[Live] Current Accel Mag: {mag:.4f}g   ")
            sys.stdout.flush()
            
            # Check if any new events were generated
            current_count = len(detector.events)
            if current_count > last_evt_count:
                new_evts = list(detector.events)[-(current_count - last_evt_count):]
                last_evt_count = current_count
                
                for ev in new_evts:
                    now = time.time()
                    
                    # Check if this is a significant vibration event (using calibration filter)
                    sev_match = ev['sev'] in severity_filter
                    mag_match = trigger_magnitude <= 0 or ev['amp'] >= trigger_magnitude
                    
                    if sev_match and mag_match:
                        
                        # Start tracking if not already tracking
                        if vibration_start_time is None:
                            vibration_start_time = now
                            # sys.stdout.write(f"\n[Tracking Started]\n")
                        
                        last_vibration_time = now
                        
                        # Check if we've been continuously vibrating for the required timeframe
                        duration = now - vibration_start_time
                        if duration >= timeframe:
                            if now - last_play_time > cooldown:
                                sys.stdout.write(f"\n[{ev['tstr']}] {ev['sym']} Continuous vibration for {duration:.1f}s! -> Playing sound!\n")
                                sys.stdout.flush()
                                play_sound(args.mp3_file)
                                last_play_time = now
                                # Reset state after playing
                                vibration_start_time = None
                                last_vibration_time = None
                                break
            
            # Reset the continuous tracking if too much time has passed without a significant event
            now = time.time()
            if vibration_start_time is not None and last_vibration_time is not None:
                if now - last_vibration_time > tolerance:
                    # sys.stdout.write(f"\n[Tracking Reset, too quiet]\n")
                    vibration_start_time = None
                    last_vibration_time = None

            time.sleep(0.01)

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\nExiting...")
        sys.exit(0)
    except Exception as e:
        print(f"Error: {e}")
